module.exports = {
    statuses: [
        {
            created_at: 'Thu Aug 20 16:57:23 +0000 2020',
            id: 1296491532636369000,
            id_str: '1296491532636368898',
            text:
                'chicos con todo respeto, cómo verga va a estar un cuarto de millón de pesos una computadora? ni aunque tengas que h… https://t.co/8V9EHt1DF6',
            truncated: true,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            is_quote_status: false,
            retweet_count: 0,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            lang: 'es',
        },
        {
            created_at: 'Thu Aug 20 16:57:23 +0000 2020',
            id: 1296491530627231700,
            id_str: '1296491530627231744',
            text:
                'RT @httpxcntrrs_: NASA jacket, pls. 🥺❤ https://t.co/LRTIOOxLK1',
            truncated: false,
            entities: [Object],
            extended_entities: [Object],
            metadata: [Object],
            source:
                '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            retweeted_status: [Object],
            is_quote_status: false,
            retweet_count: 6190,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            possibly_sensitive: false,
            lang: 'tl',
        },
        {
            created_at: 'Thu Aug 20 16:57:21 +0000 2020',
            id: 1296491523387818000,
            id_str: '1296491523387817985',
            text:
                'RT @maximaxoo: #Space: M45, the lovely Pleiades #StarCluster &amp; its striking blue reflection #nebula\n' +
                'https://t.co/OsXmsLQzog via @apod https…',
            truncated: false,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            retweeted_status: [Object],
            is_quote_status: false,
            retweet_count: 13,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            possibly_sensitive: false,
            lang: 'en',
        },
        {
            created_at: 'Thu Aug 20 16:57:20 +0000 2020',
            id: 1296491519373906000,
            id_str: '1296491519373905920',
            text: "@NASA_thaanks isn't it ALWAYS after 1 am",
            truncated: false,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
            in_reply_to_status_id: 1296238590821830700,
            in_reply_to_status_id_str: '1296238590821830656',
            in_reply_to_user_id: 1295699495049715700,
            in_reply_to_user_id_str: '1295699495049715715',
            in_reply_to_screen_name: 'NASA_thaanks',
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            is_quote_status: false,
            retweet_count: 0,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            lang: 'en',
        },
        {
            created_at: 'Thu Aug 20 16:57:20 +0000 2020',
            id: 1296491518866456600,
            id_str: '1296491518866456582',
            text:
                'RT @ToriNicksWho: My favorite part in Black is King is when they showed that black people have a cosmic footprint. I love to remind people…',
            truncated: false,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            retweeted_status: [Object],
            is_quote_status: false,
            retweet_count: 25,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            lang: 'en',
        },
        {
            created_at: 'Thu Aug 20 16:57:19 +0000 2020',
            id: 1296491514990911500,
            id_str: '1296491514990911492',
            text: 'I want to be an astronaut #NASA @NASA',
            truncated: false,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            is_quote_status: false,
            retweet_count: 0,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            lang: 'en',
        },
        {
            created_at: 'Thu Aug 20 16:57:18 +0000 2020',
            id: 1296491512340021200,
            id_str: '1296491512340021248',
            text:
                'RT @tass_agency: ⚡На МКС произошла утечка воздуха. Экипаж станции изолируется в российском модуле:\n' +
                'https://t.co/girjme8wTT\n' +
                '\n' +
                'Фото: © NASA ht…',
            truncated: false,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            retweeted_status: [Object],
            is_quote_status: false,
            retweet_count: 27,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            possibly_sensitive: false,
            lang: 'ru',
        },
        {
            created_at: 'Thu Aug 20 16:57:18 +0000 2020',
            id: 1296491512189145000,
            id_str: '1296491512189145090',
            text: '@jecikaah @OOTDFESS Mau yg NASA',
            truncated: false,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
            in_reply_to_status_id: 1296458367481847800,
            in_reply_to_status_id_str: '1296458367481847813',
            in_reply_to_user_id: 1169239755508240400,
            in_reply_to_user_id_str: '1169239755508240384',
            in_reply_to_screen_name: 'jecikaah',
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            is_quote_status: false,
            retweet_count: 0,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            lang: 'in',
        },
        {
            created_at: 'Thu Aug 20 16:57:16 +0000 2020',
            id: 1296491502101815300,
            id_str: '1296491502101815300',
            text:
                'RT @NASASpaceflight: Blue Origin-Led National Team  Delivers  Lunar Lander Engineering Mockup to  NASA.\n' +
                '\n' +
                'Presser:\n' +
                'https://t.co/XzIVretyJ3…',
            truncated: false,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            retweeted_status: [Object],
            is_quote_status: false,
            retweet_count: 33,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            possibly_sensitive: false,
            lang: 'en',
        },
        {
            created_at: 'Thu Aug 20 16:57:13 +0000 2020',
            id: 1296491491502809000,
            id_str: '1296491491502809089',
            text:
                'With Poles shifting faster than ever, humans ll be trapped on this planet n lose connection with the universe, we g… https://t.co/C2lJzwUkDc',
            truncated: true,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            is_quote_status: false,
            retweet_count: 0,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            possibly_sensitive: false,
            lang: 'en',
        },
        {
            created_at: 'Thu Aug 20 16:57:12 +0000 2020',
            id: 1296491486691971000,
            id_str: '1296491486691971079',
            text:
                "ngayon ko lang natututunan yung mga inexpect kong matutunan nung nasa college pa 'ko\n" +
                '\n' +
                "hay hay hay :'3",
            truncated: false,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            is_quote_status: false,
            retweet_count: 0,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            lang: 'tl',
        },
        {
            created_at: 'Thu Aug 20 16:57:12 +0000 2020',
            id: 1296491485815287800,
            id_str: '1296491485815287808',
            text:
                'Nasa punto ako ng buhay ko na tuwing umaga mas inuuna kong i-check ang email ko kesa sa messenger.',
            truncated: false,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            is_quote_status: false,
            retweet_count: 0,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            lang: 'tl',
        },
        {
            created_at: 'Thu Aug 20 16:57:10 +0000 2020',
            id: 1296491479381180400,
            id_str: '1296491479381180416',
            text:
                'RT @GraceSpelman: .@NASA is it true u don’t want aliens knowing about pussy https://t.co/4kR5s87m8i',
            truncated: false,
            entities: [Object],
            extended_entities: [Object],
            metadata: [Object],
            source:
                '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            retweeted_status: [Object],
            is_quote_status: false,
            retweet_count: 847,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            possibly_sensitive: false,
            lang: 'en',
        },
        {
            created_at: 'Thu Aug 20 16:57:08 +0000 2020',
            id: 1296491469507895300,
            id_str: '1296491469507895297',
            text:
                'Crew Spending Weekend in Station’s Russian Segment https://t.co/CcK1iBvw7n',
            truncated: false,
            entities: [Object],
            metadata: [Object],
            source: '<a href="https://ifttt.com" rel="nofollow">IFTTT</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            is_quote_status: false,
            retweet_count: 0,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            possibly_sensitive: false,
            lang: 'en',
        },
        {
            created_at: 'Thu Aug 20 16:57:08 +0000 2020',
            id: 1296491468786409500,
            id_str: '1296491468786409472',
            text:
                'RT @Jose_Antonio_G: ASTEROID / ABOUT 6 METERS IN DIAMETER\n' +
                'An asteroid, the size of a van, "skims" the Earth and NASA cannot detect it in ti…',
            truncated: false,
            entities: [Object],
            metadata: [Object],
            source:
                '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
            in_reply_to_status_id: null,
            in_reply_to_status_id_str: null,
            in_reply_to_user_id: null,
            in_reply_to_user_id_str: null,
            in_reply_to_screen_name: null,
            user: [Object],
            geo: null,
            coordinates: null,
            place: null,
            contributors: null,
            retweeted_status: [Object],
            is_quote_status: false,
            retweet_count: 1,
            favorite_count: 0,
            favorited: false,
            retweeted: false,
            lang: 'en',
        },
    ],
    search_metadata: {
        completed_in: 0.116,
        max_id: 1296491532636369000,
        max_id_str: '1296491532636368898',
        next_results: '?max_id=1296491468786409471&q=nasa&include_entities=1',
        query: 'nasa',
        refresh_url: '?since_id=1296491532636368898&q=nasa&include_entities=1',
        count: 15,
        since_id: 0,
        since_id_str: '0',
    },
};
